name: release

on:
  push:
    tags:
      - '*-alpha.*'

jobs:
  publish_beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          corepack-enable: true
          registry-url: 'https://registry.npmjs.org'

      - name: Deps
        run: |
          npm i -g corepack@latest
          corepack enable 
          pnpm i --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Publish
        run: |
          pnpm publish:ci --dist-tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
