name: release

on:
  push:
    tags-ignore:
      - '*-alpha.*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          corepack-enable: true
          registry-url: 'https://registry.npmjs.org'

      - name: Deps
        run: |
          npm i -g corepack@latest
          corepack enable 
          pnpm i --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Publish
        run: |
          pnpm publish:ci